name: Check Submodule Updates

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write
jobs:
  check_submodule_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1
        token: ${{ secrets.RSS_REPO_TOKEN }}

    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.COMMONPNG_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Get latest commonpng commit hash
      id: get_png_commit
      run: |
        echo "LATEST_PNG_COMMIT=$(git ls-remote git@github.com:asfu222/commonpng.git HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Check for updates
      id: check_update
      run: |
        echo "Checking submodules..."
        UPDATED=false
        for submodule in $(git config --file .gitmodules --get-regexp path | awk '{print $2}'); do
          url=$(git config --file .gitmodules --get-regexp "submodule.$submodule.url" | awk '{print $2}')
          echo "Checking submodule: $submodule"
          export GIT_ASKPASS=$(mktemp)
          echo "echo '${{ secrets.RSS_REPO_TOKEN }}'" > $GIT_ASKPASS
          chmod +x $GIT_ASKPASS
          current=$(git rev-parse HEAD:$submodule)
          latest=$(git ls-remote "$url" refs/heads/main | awk '{print $1}')
          rm -f $GIT_ASKPASS  # Cleanup auth helper
          echo "'$submodule': Current commit: $current, Latest commit: $latest"
          if [ "$current" != "$latest" ]; then
            echo "Submodule '$submodule' has an update."
            UPDATED=true
          else
            echo "No update for submodule '$submodule'."
          fi
        done
        echo "Checking if commonpng commit has changed..."
        if [ -f assets/static/bundle_version.hash ]; then
          old_commit=$(cut -d'-' -f2 < assets/static/bundle_version.hash)
        else
          old_commit=""
        fi
        echo "Old commit: $old_commit"
        echo "Latest commit: ${{ steps.get_png_commit.outputs.LATEST_PNG_COMMIT }}"
        if [ "$old_commit" != "${{ steps.get_png_commit.outputs.LATEST_PNG_COMMIT }}" ]; then
          echo "Commonpng commit updated."
          UPDATED=true
        else
          echo "No update in commonpng commit."
          UPDATED=false
        fi
        echo "SUBMODULE_STATUS=$UPDATED" >> $GITHUB_OUTPUT

    - name: Trigger follow-up workflow if update detected
      if: steps.check_update.outputs.SUBMODULE_STATUS == 'true'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "run-deployment"}'
